name: Build

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Prepare a docker container for build
        uses: docker/build-push-action@v2
        with:
          context: tools
          tags: spike-rt-builder:latest
          push: false
      - name: Build test
        uses: addnab/docker-run-action@v3
        with:
          image: spike-rt-builder:latest
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            ./scripts/build-test.sh
