name: Container

on:
  push:
    branches:
      - main
    paths:
      - '**.dockerfile'
  workflow_dispatch:

jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push slim
        uses: docker/build-push-action@v3
        with:
          context: tools/docker
          file: tools/docker/slim.dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/spike-rt:latest
            ghcr.io/${{ github.repository_owner }}/spike-rt:slim
          cache-from: type=gha,scope=slim
          cache-to: type=gha,mode=max,scope=slim
      - name: Build and push rich
        uses: docker/build-push-action@v3
        with:
          context: tools/docker
          file: tools/docker/rich.dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spike-rt:rich
          cache-from: type=gha,scope=rich
          cache-to: type=gha,mode=max,scope=rich
