name: GitHub Pages

on:
  push:
    branches: main
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
permissions:
  contents: read
  pages: write
  id-token: write
 
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
 
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
 
      - name: Prepare build directory for Doxygen
        run: mkdir -p drivers/build-doxygen/
      - name: Build Doxygen-en
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          working-directory: drivers/
          doxyfile-path: Doxyfile-en
      - name: Build Doxygen-ja
        uses: mattnotmitt/doxygen-action@v1.9.4
        with:
          working-directory: drivers/
          doxyfile-path: Doxyfile-ja

      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'drivers/build-doxygen/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
